spring: 
  profiles: 
    active: local #local,dev,real
  
  mvc:
    view: #view 경로 및 확장자 지정
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource: #DB 접속
    driver-class-name: software.aws.rds.jdbc.mysql.Driver
    url: jdbc:mysql:aws://database-wlsdudzksn.ctuuiua2exdw.ap-northeast-2.rds.amazonaws.com:3306
    username: admin
    password: Kanu0716!!
    hikari: #커넥션풀 
      connection-timeout : 30000 #클라이언트가 pool에 connection을 요청하는데 기다리는 최대시간을 설정 30초
      maximum-pool-size : 10 #최대 커넥션 개수 설정
      max-lifetime : 1800000  #커넥션 풀에서 살아있을 수 있는 커넥션의 최대 수명시간 1,800초(30분)
      
  messages: #메시지
    basename: messages.validation
    encoding: UTF-8
    
  devtools: #View reload    livereload:      enabled: true
    
    restart: #컨트롤러, 모델단이 바뀌었을 때 프로젝트 재시작 설정 (정확히는 classpath에 있는 모든 파일)      enabled: true #재시작 하지 않음

mybatis: #mybatis 설정
  type-aliases-package: kr.spring.**.vo 
  mapper-locations: kr/spring/**/dao/*.xml
  
logging: #로그 지정  level:
    #root: error    '[kr.spring]': debug 
    #com.zaxxer.hikari.HikariConfig: DEBUG
    #com.zaxxer.hikari: TRACE 
    
server:
  port: 8080
  servlet:
    context-path: /mybatisMysql
    encoding:
      charset: UTF-8
      enabled: true #http 인코딩 지원을 활성화할지 여부
      force: true 


  
    
    
 

  
  
  